# Generated by Django 5.1.7 on 2025-04-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oeuvre',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
